name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        export LOCAL_DIR=$(pwd)
        mkdir ./bin
        wget -P ./bin http://commondatastorage.googleapis.com/git-repo-downloads/repo
        chmod +x ./bin/repo
        mkdir ./conix-core
        cd ./conix-core
        ${LOCAL_DIR}/bin/repo init -u https://github.com/MaksymPrymierov/Conix-Core_manifest
        ${LOCAL_DIR}/bin/repo sync
        cd Conix-Core
        make
