name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        cd ~/
        mkdir bin
        wget -P ~/bin http://commondatastorage.googleapis.com/git-repo-downloads/repo
        mkdir conix-core
        cd conix-core
        ~/bin/repo init -u https://github.com/MaksymPrymierov/Conix-Core_manifest
        ~/bin/repo sync
        cd Conix-Core
        make
